plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
        config: .eslintrc
        extensions:
        - .es6
        - .js
checks:
  method-lines:
    enabled: false

exclude_patterns:
  - "*.config.*"
  - "tools/*"
  - "package.json"
